# 
# Home Assistant Automation Blueprint
#
# Synchronize on/off states on four devices
#
# Revision 1.3 - Added condition to handle unavailable states
# Modified by Johan Schelin, Apr. 2021
#

blueprint:
  name: Synchronize Four States
  description: Bind four entities together to act in unison (selected entites must
    all support the same state values). In this version restricted to on/off
  domain: automation
  input:
    switch_1:
      name: Entity 1
      selector:
        entity: {}
    switch_2:
      name: Entity 2
      selector:
        entity: {}
    switch_3:
      name: Entity 3
      default:
      selector:
        entity: {}
    switch_4:
      name: Entity 4
      default:
      selector:
        entity: {}
  source_url: https://github.com/ruddj/ha_blueprints/blob/main/SyncStatesFour.yaml
mode: single
max_exceeded: silent
variables:
  switch_1: !input 'switch_1'
  switch_2: !input 'switch_2'
  switch_3: !input 'switch_3'
  switch_4: !input 'switch_4'
trigger:
- platform: state
  entity_id: 
    - !input 'switch_1'
    - !input 'switch_2'
    - !input 'switch_3'
    - !input 'switch_4'
  from:
    - 'on'
    - 'off'
condition:
- condition: template
  value_template: '{{ states(switch_1) != ''unavailable'' }}'
- condition: template
  value_template: '{{ states(switch_2) != ''unavailable'' }}'
- condition: template
  value_template: '{{ states(switch_3) != ''unavailable'' }}'
- condition: template
  value_template: '{{ states(switch_4) != ''unavailable'' }}'
action:
  - service: homeassistant.turn_{{ trigger.to_state.state }}
    data:
      entity_id: '{% if trigger.from_state.entity_id == switch_1 %} {{ switch_2 }} {% elif trigger.from_state.entity_id == switch_2 %} {{ switch_1 }} {% elif trigger.from_state.entity_id == switch_3 %} {{ switch_1 }} {% else %}  {{ switch_1 }}  {% endif %}'
  - service: homeassistant.turn_{{ trigger.to_state.state }}
    data:
      entity_id: '{% if trigger.from_state.entity_id == switch_1 %} {{ switch_3 }} {% elif trigger.from_state.entity_id == switch_2 %} {{ switch_3 }} {% elif trigger.from_state.entity_id == switch_3 %} {{ switch_2 }} {% else %}  {{ switch_2 }}  {% endif %}'
  - service: homeassistant.turn_{{ trigger.to_state.state }}
    data:
      entity_id: '{% if trigger.from_state.entity_id == switch_1 %} {{ switch_4 }} {% elif trigger.from_state.entity_id == switch_2 %} {{ switch_4 }} {% elif trigger.from_state.entity_id == switch_3 %} {{ switch_4 }} {% else %}  {{ switch_3 }}  {% endif %}'
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 200